# Generated by Django 4.0.2 on 2022-03-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0002_profile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../media/profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
